# Generated by Django 4.2 on 2025-06-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_type', models.CharField(choices=[('FEEDING', 'Кормление'), ('WEIGHT', 'Взвешивание'), ('VET', 'Ветеринарный осмотр')], max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=3000)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='animals.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.section'),
        ),
    ]
