name: Django CI with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d --build
        docker-compose exec -T web python manage.py migrate
        docker-compose exec -T web python manage.py test

    - name: Tear down
      if: always()
      run: docker-compose down
