name: Django with docker compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            curl \
            python3 \
            python3-pip \
            python3-venv \
            docker-compose

    - name: Set up docker compose
      run: |
        sudo docker-compose -f docker-compose.yml up -d --build
        sudo docker-compose exec -T web python manage.py migrate
        sudo docker-compose exec -T web python manage.py test

    - name: Docker compose down
      if: always()
      run: docker-compose down
